---
# tasks file for mysql
- name: init myCNF
  shell: printf '[client]\n
    user=root\n
    password=\n' >> /home/ubuntu/.my.cnf

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Create mysql user
  mysql_user: 
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:ALL